language: python
python:
  - "2.7"
  - "3.4"
install:
  - pip install -r requirements_for_test.txt
  - pip install -e .
script:
  - ./scripts/run_tests.sh --cov=dmutils --cov-report=term-missing
after_success:
  - coveralls
notifications:
  email: false
