language: python
python:
  - "3.6"
install:
  - export BOTO_CONFIG=/dev/null
  - pip install -r requirements-dev.txt
script:
  - ./scripts/run_tests.sh --cov=dmutils --cov-report=term-missing
after_success:
  - coveralls
notifications:
  email: false
